# Generated by Django 4.0.3 on 2022-03-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='LogoEntreprise'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='site_web',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
