# Generated by Django 4.0.3 on 2022-03-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0002_entreprise_description_entreprise_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='slug',
            field=models.SlugField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
