# Generated by Django 4.0.3 on 2022-05-08 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0002_rename_diplome_profile_libelle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='poste',
        ),
    ]
