# Generated by Django 4.0.3 on 2022-05-08 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0003_remove_profile_poste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='département',
            new_name='departement',
        ),
    ]
