# Generated by Django 4.0.3 on 2022-05-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0004_rename_département_profile_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='description_courte',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='etudes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='evolution_carriere',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='departement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salaire',
            field=models.CharField(max_length=300),
        ),
    ]
