# Generated by Django 4.0.3 on 2022-05-10 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0005_profile_description_profile_description_courte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='departement',
        ),
    ]
