# Generated by Django 4.0.3 on 2022-05-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0006_remove_profile_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='secteur',
            field=models.TextField(blank=True),
        ),
    ]
