# Generated by Django 4.0.3 on 2022-05-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0007_profile_secteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recrute',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
