# Generated by Django 4.0.3 on 2022-05-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0010_alter_profile_secteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='secteur',
            field=models.CharField(max_length=200),
        ),
    ]
