# Generated by Django 4.0.3 on 2022-05-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_utilisateur_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='diplome',
            field=models.CharField(default='master finance', max_length=300),
            preserve_default=False,
        ),
    ]
