# Generated by Django 4.0.3 on 2022-05-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_utilisateur_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='entreprise',
            field=models.CharField(default='thales', max_length=300),
            preserve_default=False,
        ),
    ]
