# Generated by Django 4.0.3 on 2022-05-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_utilisateur_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='mail',
            field=models.EmailField(default='simon.martinenq@efrei.net', max_length=254),
            preserve_default=False,
        ),
    ]
